export interface Movie {
  id: number;
  title: string;
  poster_path: string;
  genres: string[];
  rating: number;
  year: number;
  description: string;
  keywords: string[];
  mood: string[];
  imdb_id?: string;
  trailer_url?: string;
}

export const movies: Movie[] = [
  {
    id: 1,
    title: "Interstellar",
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    rating: 8.7,
    year: 2014,
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    keywords: ["space", "exploration", "time", "wormhole"],
    mood: ["inspired", "thoughtful", "epic"],
  },
  {
    id: 2,
    title: "The Dark Knight",
    poster_path: "/qJ2tW6WMUDux911BTUgMe1nFGDB.jpg",
    genres: ["Action", "Crime", "Drama"],
    rating: 9.0,
    year: 2008,
    description: "When the menace known as the Joker wreaks havoc on Gotham, Batman must confront one of the greatest tests.",
    keywords: ["batman", "joker", "gotham", "hero"],
    mood: ["intense", "thrilling", "dark"],
  },
  {
    id: 3,
    title: "Inception",
    poster_path: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    genres: ["Sci-Fi", "Action", "Thriller"],
    rating: 8.8,
    year: 2010,
    description: "A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea.",
    keywords: ["dreams", "heist", "mind", "layers"],
    mood: ["mind-bending", "thrilling", "intense"],
  },
  {
    id: 4,
    title: "The Shawshank Redemption",
    poster_path: "/9cjIGRSQL7nPBqdaNkfE0jbXkGL.jpg",
    genres: ["Drama"],
    rating: 9.3,
    year: 1994,
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    keywords: ["prison", "hope", "friendship", "redemption"],
    mood: ["hopeful", "inspiring", "emotional"],
  },
  {
    id: 5,
    title: "Pulp Fiction",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    genres: ["Crime", "Drama"],
    rating: 8.9,
    year: 1994,
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    keywords: ["crime", "nonlinear", "gangster"],
    mood: ["edgy", "cool", "intense"],
  },
  {
    id: 6,
    title: "The Grand Budapest Hotel",
    poster_path: "/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    genres: ["Comedy", "Drama", "Adventure"],
    rating: 8.1,
    year: 2014,
    description: "A writer encounters the owner of an aging high-class hotel, who tells of his early years serving as a lobby boy.",
    keywords: ["hotel", "quirky", "vintage", "adventure"],
    mood: ["whimsical", "fun", "charming"],
  },
  {
    id: 7,
    title: "Parasite",
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    genres: ["Thriller", "Drama", "Comedy"],
    rating: 8.5,
    year: 2019,
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    keywords: ["class", "social", "twist", "family"],
    mood: ["intense", "thought-provoking", "dark"],
  },
  {
    id: 8,
    title: "La La Land",
    poster_path: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    genres: ["Romance", "Drama", "Musical"],
    rating: 8.0,
    year: 2016,
    description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations.",
    keywords: ["music", "love", "dreams", "jazz"],
    mood: ["romantic", "dreamy", "bittersweet"],
  },
  {
    id: 9,
    title: "Mad Max: Fury Road",
    poster_path: "/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    genres: ["Action", "Adventure", "Sci-Fi"],
    rating: 8.1,
    year: 2015,
    description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland.",
    keywords: ["apocalypse", "chase", "desert", "survival"],
    mood: ["adrenaline", "intense", "epic"],
  },
  {
    id: 10,
    title: "The Hangover",
    poster_path: "/uluhlXubGu1VxU63X9VHCLWDAYP.jpg",
    genres: ["Comedy"],
    rating: 7.7,
    year: 2009,
    description: "Three buddies wake up from a bachelor party in Las Vegas with no memory of the previous night and the bachelor missing.",
    keywords: ["vegas", "party", "comedy", "bachelor"],
    mood: ["funny", "wild", "lighthearted"],
  },
  {
    id: 11,
    title: "Spirited Away",
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    genres: ["Animation", "Fantasy", "Adventure"],
    rating: 8.6,
    year: 2001,
    description: "During her family's move, a young girl wanders into a world ruled by gods, witches, and spirits.",
    keywords: ["anime", "fantasy", "magical", "journey"],
    mood: ["magical", "whimsical", "emotional"],
  },
  {
    id: 12,
    title: "The Silence of the Lambs",
    poster_path: "/uS9m8OBk1RVfUPynE4noK3Bmu4w.jpg",
    genres: ["Thriller", "Horror", "Crime"],
    rating: 8.6,
    year: 1991,
    description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer.",
    keywords: ["serial killer", "fbi", "psychological"],
    mood: ["scary", "intense", "dark"],
  },
  {
    id: 13,
    title: "Forrest Gump",
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    genres: ["Drama", "Romance", "Comedy"],
    rating: 8.8,
    year: 1994,
    description: "The presidencies of Kennedy and Johnson through the eyes of an Alabama man with an IQ of 75.",
    keywords: ["history", "life", "running", "love"],
    mood: ["heartwarming", "inspiring", "emotional"],
  },
  {
    id: 14,
    title: "Gravity",
    poster_path: "/kZ2nZw8dp0Hhicg1iCJJmRkAJBk.jpg",
    genres: ["Sci-Fi", "Thriller", "Drama"],
    rating: 7.7,
    year: 2013,
    description: "Two astronauts work together to survive after an accident leaves them stranded in space.",
    keywords: ["space", "survival", "astronaut"],
    mood: ["tense", "breathtaking", "intense"],
  },
  {
    id: 15,
    title: "The Martian",
    poster_path: "/5BHuvQ6p9kfc091Z8RiFNhCwL4b.jpg",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    rating: 8.0,
    year: 2015,
    description: "An astronaut becomes stranded on Mars and must devise a way to signal that he is alive.",
    keywords: ["mars", "survival", "science", "space"],
    mood: ["inspiring", "hopeful", "thrilling"],
  },
  {
    id: 16,
    title: "Whiplash",
    poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    genres: ["Drama", "Music"],
    rating: 8.5,
    year: 2014,
    description: "A promising young drummer enrolls at a cut-throat music conservatory under the tutelage of a ruthless instructor.",
    keywords: ["music", "ambition", "jazz", "obsession"],
    mood: ["intense", "driven", "gripping"],
  },
  {
    id: 17,
    title: "Superbad",
    poster_path: "/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg",
    genres: ["Comedy"],
    rating: 7.6,
    year: 2007,
    description: "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-fueled party goes awry.",
    keywords: ["highschool", "party", "friendship"],
    mood: ["funny", "lighthearted", "nostalgic"],
  },
  {
    id: 18,
    title: "Blade Runner 2049",
    poster_path: "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    genres: ["Sci-Fi", "Drama", "Thriller"],
    rating: 8.0,
    year: 2017,
    description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.",
    keywords: ["replicant", "future", "dystopia"],
    mood: ["atmospheric", "contemplative", "dark"],
  },
  {
    id: 19,
    title: "The Notebook",
    poster_path: "/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg",
    genres: ["Romance", "Drama"],
    rating: 7.8,
    year: 2004,
    description: "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom.",
    keywords: ["love", "passion", "romance", "memory"],
    mood: ["romantic", "emotional", "heartwarming"],
  },
  {
    id: 20,
    title: "Get Out",
    poster_path: "/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    genres: ["Horror", "Thriller", "Mystery"],
    rating: 7.7,
    year: 2017,
    description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
    keywords: ["race", "horror", "psychological", "twist"],
    mood: ["unsettling", "intense", "thought-provoking"],
  },
];

export const suggestedPrompts = [
  "I feel like watching something funny tonight",
  "Suggest a sci-fi movie like Interstellar",
  "I want a romantic movie",
  "Show me something thrilling and dark",
  "Recommend an inspiring feel-good movie",
];
